models.py 구현
wecode-bootcamp-korea/19-1st-Market-ChoKurly-backend pull request #1
Opened 2021-04-14 04:51 UTC by ahnjeonghyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users app 생성 및 models.py 정의
- products app 생성 및 models.py 정의
- orders app 생성 및 models.py 정의

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [O] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [O] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [O] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [O] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-14 05:46 UTC, ahnjeonghyun commented
test

2021-04-14 07:33 UTC, ulfrid requested changes
확인 바랍니다~!

2021-04-14 07:33 UTC, devops-andrew commented on orders/models.py
> +    payment_type       =   models.ForeignKey('PaymentType',on_delete = models.CASCADE,null=True)
```suggestion
    payment_type       =   models.ForeignKey('PaymentType',on_delete = models.CASCADE,null=True)
```
전반적으로 CASCADE를 많이 사용하시는데, 이게 간편하지만, 나중에 데이터 조작시에 문제가 될 수 있습니다. 연관된 모든 데이터가 날아 갈수 있어서. SET_NULL, 권장드립니다. SET_NULL 하려면 null=True여야 합니다.

2021-04-14 07:33 UTC, devops-andrew commented on orders/models.py
> +    shipping_method    =   models.CharField(max_length=45,null=True)
Shipping 수단에 대해서 여러가지가 있을텐데 스트링으로 처리하면 나중에 로직에서 스트링으로 비교하게 되는데 장기적으로는 문제가 됩니다. 수단이 늘어날때마다 코드를 수정해야 겠죠? 테이블로 따로 빼주세요.

2021-04-14 07:33 UTC, devops-andrew commented on products/models.py
> +    stock           =   models.IntegerField()
재고 수량에 -가 없다면  PositiveIntegerField를 써서 양의 정수만 저장하는 필드를 사용헤보시는건 어떨까요?

2021-04-14 07:33 UTC, devops-andrew commented on products/models.py
> +    img_url         = models.CharField(max_length=500)
```suggestion
    image_url         = models.URLField(max_length=2000)
```
필드명은 줄임말을 지양해주시고, URLField라는 것이 있습니다. 물론 컨벤션입니다. 필드효과는 장고의 form이라는 것을 써야 효과가 있는데 우리는 과정상 사용하지 않습니다. 그래서 기능상으로는 CharField와 같습니다.
그리고 url을 다룰때는 길이제한이 짧으면 좋지 않으므로, 최소 2000자 길이는 주도록 합시다.

2021-04-14 07:33 UTC, ulfrid commented on users/models.py
> +    gender              =   models.CharField(max_length=10, choices=(('남','남자'),('여','여자')))
좋은 아이디어 입니다. 다만 choices에 있는 데이터가 프론트에서는 로직을 처리하게 될텐데 이게 호용성이 있는지 궁금합니다.

2021-04-15 01:18 UTC, ulfrid requested changes
확인 바랍니다~! 리뷰 메세지에 답해주세요.

2021-04-15 01:18 UTC, ulfrid commented on users/models.py
> +    is_default          =   models.SmallIntegerField()
```suggestion
    is_default          =   models.BooleanField(default=False)
```
BooleanField가 있습니다! 
https://docs.djangoproject.com/en/3.2/ref/models/fields/#booleanfield

2021-04-15 01:18 UTC, ulfrid commented on users/models.py
> +
리뷰에 이미지 저장하는 기능은 없나요?

2021-04-15 01:18 UTC, ulfrid commented on products/models.py
> +        db_table = 'allegyproducts'
```suggestion
        db_table = 'allegy_products'
```
컨벤션상 이어지는 단어는 언더스코어로 구분해주세요.

2021-04-15 01:18 UTC, ulfrid commented on products/models.py
> +        db_table = 'allegyproducts'
다른 테이블 이름들도 연결 단어는 변경해주세요.

2021-04-15 01:18 UTC, ulfrid commented on orders/models.py
> +    total_quantity     =   models.IntegerField(null=True)
```suggestion
    total_quantity     =   models.IntegerField(default=0)
```
null True도 좋지만 어차피 숫자가 기록될 곳이라면 null 보다는 기본값 0을 주는건 어떨까요?

2021-04-15 01:18 UTC, ulfrid commented on orders/models.py
> +    quantity         =   models.IntegerField()
마찬가지 null or default 적용 해주세요.

2021-04-15 01:18 UTC, ulfrid commented on products/models.py
> +    stock           =   models.PositiveIntegerField()
여기도 마찬가지 입니다. null or  default

2021-04-15 06:54 UTC, ahnjeonghyun commented on orders/models.py
> +    shipping_method    =   models.CharField(max_length=45,null=True)
수정 완료 했습니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on products/models.py
> +    img_url         = models.CharField(max_length=500)
수정 완료 했습니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on orders/models.py
> +    payment_type       =   models.ForeignKey('PaymentType',on_delete = models.CASCADE,null=True)
SET_NULL은 고심끝에 꼭 삭제 되야하는 것들 빼고는 수정하였습니다. 리뷰 부탁드립니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on orders/models.py
> +    total_quantity     =   models.IntegerField(null=True)
수정 완료 했습니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on orders/models.py
> +    quantity         =   models.IntegerField()
카트에는 무조건 한개이상의 상품이 담길 수 밖에없는데 null 또는 default 값을 왜 줘야하는지 궁금합니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on products/models.py
> +    stock           =   models.PositiveIntegerField()
수정 완료 했습니다.

2021-04-15 06:54 UTC, ahnjeonghyun commented on products/models.py
> +        db_table = 'allegyproducts'
수정 완료 했습니다.

2021-04-15 07:17 UTC, fcfargo commented on users/models.py
> +    is_default          =   models.SmallIntegerField()
BolleanField로 수정했습니다~

2021-04-15 07:23 UTC, ulfrid commented
LGTM~ 👍

2021-04-15 07:23 UTC, merged