[19기 백승찬] add: 상품 필터 기능 구현
wecode-bootcamp-korea/19-1st-Market-ChoKurly-backend pull request #11
Opened 2021-04-20 04:30 UTC by poketsc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 필터 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상품 필터 기능 구현
- 기존에 merge된 productview 에서 ('product_count',7) -> ('product_count',9)로 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 사실 productview 와 productfilterview 를 하나의 뷰로 합쳐서 할수도 있지만 기능 이름의 명확한 분리를 위해 나누어서 구현했습니다~

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-20 05:30 UTC, ulfrid requested changes

2021-04-20 05:30 UTC, ulfrid commented on products/urls.py
>      path('/product', ProductView.as_view()),
이제와서 발견한건데 이미 /products 로 시작하는 경로아닌가요? 그럼 그냥 중복안되게 '' 로 주는게 나을것 같습니다.
```suggestion
    path('', ProductView.as_view()),
```

2021-04-20 05:30 UTC, ulfrid commented on products/urls.py
> +    path('/productfilter', ProductFilterView.as_view())
```suggestion
    path('/filter', ProductFilterView.as_view())
```
여기도 중복 문자열은 줄이는게 좋겠죠

2021-04-20 05:30 UTC, ulfrid commented on products/views.py
>          return JsonResponse({'results':results}, status=200)
어떤 차이점때문에 이뷰가 생겨야하는지 코드만 봐서는 와닿지 않는데 구현 목적 페이지와 결과의 차이를 알수있는 캡쳐를 제시해주세요.

2021-04-20 07:12 UTC, poketsc commented on products/urls.py
>      path('/product', ProductView.as_view()),
list로 수정했습니다~

2021-04-20 07:12 UTC, poketsc commented on products/urls.py
> +    path('/productfilter', ProductFilterView.as_view())
productfilter 삭제 했습니다~

2021-04-20 07:13 UTC, poketsc commented on products/views.py
>          return JsonResponse({'results':results}, status=200)
ProductListView 로 변수명 바꾸고 하나로 통합 시켰습니다~

2021-04-20 08:14 UTC, ulfrid commented
잘 수정하셨습니다. 근데 이제 Pagenation을 고려해야 할것 같아요. 일반 상품 리스트의 경우, offset : limit를 받는 처리를 해서 페이지 번호당 20개 혹은 정해진 갯수대로 출력되야 하는데 이부분 확인해 주세요.

2021-04-21 01:55 UTC, ulfrid approved these changes
LGTM 👍

2021-04-21 01:56 UTC, merged