Feature/seungchan baek
wecode-bootcamp-korea/19-1st-Market-ChoKurly-backend pull request #16
Opened 2021-04-21 11:37 UTC by poketsc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 리뷰 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상품을 구매한 사람만 리뷰를 작성할 수 있도록 구현
- post,get 으로 작성 할때와 불러올때 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 잘 작동 됩니다~

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-21 23:34 UTC, ulfrid requested changes

2021-04-21 23:34 UTC, ulfrid commented on users/views.py
> +    def post(self,request,product_id):
```suggestion
    def post(self,request,product_id=None):
```
보통 그럴일은 없겠지만, product_id를 받으면 그부분에 대한 검증도 해줘야 합니다. 또 인자가 전달이 안되면 500 에러가 날텐데  이걸 방지하려면  디폴트 값을 주세요.

2021-04-21 23:34 UTC, ulfrid commented on users/views.py
> +    def post(self,request,product_id):
아래 두 메소드도 같습니다. 세개만 해결해주세요. 로직은 많이 깔끔해졌네요~👍

2021-04-22 01:53 UTC, poketsc commented on users/views.py
> +    def post(self,request,product_id):
수정 완료 했습니다~

2021-04-22 02:54 UTC, ulfrid approved these changes
LGTM 👍

2021-04-22 02:54 UTC, merged