[19기 백승찬] add:비밀번호 찾기 기능 구현
wecode-bootcamp-korea/19-1st-Market-ChoKurly-backend pull request #6
Opened 2021-04-16 08:26 UTC by poketsc

## 수정 사항 간략한 한줄 요약

- 비밀번호 찾기 구현
- 입력사항이 데이터 베이스와 매칭되는것이 존재하면  인증번호 생성
- 인증번호 생성후 데이터베이스에 해당 유저 비밀번호를 인증번호로 업데이트
- 업데이트후 이메일로 인증번호 보냄
- 해당 유저 인증번호로 로그인하게 만듬

## 기타 질문 및 특이 사항

- 인증번호 입력후 바로 새로운 비밀번호 입력받고 업데이트 하게 구현하고 싶었지만 어려워서 포기했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-17 06:08 UTC, ulfrid requested changes
확인 바랍니다

2021-04-17 06:08 UTC, devops-andrew commented on users/urls.py
> +    path('/findpw',  FindPwView.as_view()),
```suggestion
    path('/find-id', FindIdView.as_view()),
    path('/find-password',  FindPwView.as_view()),
```
이어지는 단어는 '-' 로 구분해주세요.

2021-04-17 06:08 UTC, devops-andrew commented on users/views.py
> +class FindPwView(View):
```suggestion
class FindPasswordView(View):
```
오히려 이런걸 줄이는건 지양합시다.

2021-04-17 06:08 UTC, ulfrid commented on users/views.py
> +            auth_num += random.choice(string_pool)
random string 만드시는건가요? 클래스 안에 별도 메소드로 구현하는건 어떤가요?

2021-04-17 06:08 UTC, ulfrid commented on users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_NAME OR IDENTIFICATION OR EMAIL'})
```suggestion
                return JsonResponse({'MESSAGE':'INVALID_USER'}, status=400)
```
그냥 잘 못된 사용자가  나을것 같네요, status_code 잊지마세요

2021-04-17 08:09 UTC, poketsc commented on users/urls.py
> +    path('/findpw',  FindPwView.as_view()),
수정 완료 했습니다~

2021-04-17 08:09 UTC, poketsc commented on users/views.py
> +class FindPwView(View):
수정 완료 했습니다~

2021-04-17 08:10 UTC, poketsc commented on users/views.py
> +            auth_num += random.choice(string_pool)
class 를 따로 선언해서 FindPassView에서 class 호출하는식으로 구현했습니다~

2021-04-17 08:10 UTC, poketsc commented on users/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_NAME OR IDENTIFICATION OR EMAIL'})
수정 완료 했습니다~

2021-04-17 10:46 UTC, ulfrid commented on users/views.py
> +            auth_num += random.choice(string_pool)
이 기능이 여러곳에 쓰인다면 이렇게 처리할것 같은데, 과한것 같습니다. 그리고 클래스로 구현할거면 @classmethod 공부해보시고, 적용해보세요.

2021-04-18 02:54 UTC, poketsc commented on users/views.py
> +            auth_num += random.choice(string_pool)
다시 생각해보니 class를 선언해도 다시 재사용 할 일이 없을거 같아서 FindPasswordView 안에서 함수 선언해서 만들었습니다~

2021-04-18 02:57 UTC, ulfrid approved these changes
LGTM 👍

2021-04-18 02:57 UTC, merged